### Tất cả các thuật ngữ của mạng (network) và môi trường dòng lệnh (CLI)

---------------------------------------
    THUẬT NGỮ TRONG NETWORK VÀ CLI
          ------------------
1. WAN = Wide Area Network
2. LAN = Local Area Network
3. TCP = Transmission Control Protocol
4. UDP = User Datagram Protocol
5. IP = Internet Protocol
6. UPnP = Universal Plug and Play
7. NAT = Network Address Translation
8. CGNAT = Carrier-Grade NAT
9. IPv4 = Internet Protocol version 4
10. IPv6 = Internet Protocol version 6
11. DNS = Domain Name Server
12. BSSID = Basic Service Set Identifier
13. SSID = Service Set Identifier
14. RSSI = Received Signal Strength Indicator
15. VPN = Virtual Private Network
16. APN = Access Point Name
17. WPS = Wi-Fi Protected Setup
18. WPA = Wi-Fi Protected Access
19. WPA2 = Wi-Fi Protected Access 2
20. WPA3 = Wi-Fi Protected Access 3
21. TKIP = Temporal Key Integrity Protocol
22. AES = Advanced Encryption Standard
23. MAC = Media Access Control Address
24. DHCP = Dynamic Host Configuration Protocol 
25. DMZ = Demilitarized Zone
26. SLAAC = Stateless Address Autoconfiguration
27. DHCPv6 = Dynamic Host Configuration Protocol version 6
28. PPPoE = Point-to-Point Protocol over Ethernet
29. PPPoEv6 = Point-to-Point Protocol over Ethernet IPv6
30. DUID = DHCP Unique Identifier
31. ISP = Internet Service Provider
32. PSK = Pre-Shared Key
33. WEP = Wired Equivalent Privacy
34. 802.11x = IEEE 802.11
35. 802.11b = Wi-Fi 1
36. 802.11a = Wi-Fi 2
37. 802.11g = Wi-Fi 3
38. 802.11n = Wi-Fi 4
39. 802.11ac = Wi-Fi 5
40. 802.11ax = Wi-Fi 6 / 6E
41. 802.11be = Wi-Fi 7
42. WLAN = Wireless Local Area Network
43. HTTP = Hypertext Transfer Protocol
44. HTTPS = Hypertext Transfer Protocol Secure
45. FTP = File Transfer Protocol 
46. SFTP = Secure File Transfer Protocol
47. SMTP = Simple Mail Transfer Protocol
48. POP3 = Post Office Protocol version 3
49. IMAP = Internet Message Access Protocol
50. SSH = Secure Shell
51. Telnet = Teletype Network
52. SNMP = Simple Network Management Protocol
53. NTP = Network Time Protocol
54. SCTP = Stream Control Transmission Protocol
55. QUIC = Quick UDP Internet Connection
56. ICMP = Internet Control Message Protocol
57. ARP = Address Resolution Protocol
58. RARP = Reverse Address Resolution Protocol
59. IPSec = Internet Protocol Security
60. IGMP = Internet Group Management Protocol
61. RIP = Routing Information Protocol
62. OSPF = Open Shortest Path First
63. BGP = Border Gateway Protocol
64. EIGRP = Enhanced Interior Gateway Routing Protocol
65. TLS = Transport Layer Security
66. SSL = Secure Sockets Layer
67. RADIUS = Remote Authentication Dial-In User Service
68. TACACS+ = Terminal Access Controller Access-Control System Plus
69. Kerberos = ...
70. LDAP = Lightweight Directory Access Protocol
71. Ethernet = IEEE 802.3 Standard
72. Wi-Fi = Wireless-Fidelity (IEEE 802.11)
73. PPP = Point-to-Point Protocol
74. LLC = Logical Link Control
75. VLAN = Virtual Local Area Network (IEEE 802.1Q)
76. STP = Spanning Tree Protocol
77. MQTT = Messages Queuing Telemetry Transport
78. Websockets = ...
79. RTP = Real-time Transport Protocol
80. RTCP = Real-time Transport Control Protocol
81. RTMP = Real-time Messaging Protocol
82. SIP = Session Initiation Protocol
83. H.323 = Video
84. SDP = Session Description Protocol
85. WebRTC = Web Real-Time Communication
86. CoAP = Constrained Application Protocol
87. AMQP = Advanced Messages Queuing Protocol
88. XMPP = Extensible Messaging and Presence Protocol
89. Zigbee = IEEE 802.15.4 
90. Z-Wave = Smartphone Protocol
91. SAML = Security Assertion Markup Language
92. OAuth 2.0 = Open Authorization 2.0
93. OIDC = OpenID Connect
94. MPLS = Multiprotocol Label Switching
95. ICMPv6 = Internet Control Messages Protocol version 6
96. L2TP = Layer 2 Tunneling Protocol
97. PPTP = Point-to-Point Tunneling Protocol
98. VXLAN = Virtual Extensible Local Area Network
99. LoRaWAN = Long Range Wide Area Network
100. 6LoWPAN = Internet Protocol version 6 over Low-Power Wireless Personal Area Network (IPv6 over Low-Power Wireless Personal Area Network)
101. IS-IS = Intermediate System to Intermediate System
102. iSCSI = Internet Small Computer System Interface
103. FCIP = Fibre Channel over IP (Fibre Channel over Internet Protocol)
104. Modbus = ...
105. PROFINET = Process Field Nét
106. BACnet = Building Automation and Control network
107. TTL = Time To Live
108. OpenVPN = Open Source Virtual Private Network
109. SSTP = Secure Socket Tunneling Protocol
110. IKEv2 = Internet Key Exchange version 2
111. DES = Data Encryption Standard
112. 3DES = Triple Data Encryption Standard
113. RSA = Rives-Shamir-Adleman
114. ECC = Elliptic Curve Cryptography
115. PGP = Pretty Good Privacy
116. GPG = GNU Privacy Guard
117. Wireguard = Wireguard
118. ChaCha20 = ChaCha20
119. MSCHAPv2 = Microsoft Challange Handshake Authentication Protocol version 2
120. PEAP = Protected Extensible Authentication Protocol
121. EAP-TLS = Extensible Authentication Protocol-Transport Layer Security
---------------------------------------